charTokenMapGrouped = {
    "UppercaseLetterChar": {
        "UpperA": "A",
        "UpperB": "B",
        "UpperC": "C",
        "UpperD": "D",
        "UpperE": "E",
        "UpperF": "F",
        "UpperG": "G",
        "UpperH": "H",
        "UpperI": "I",
        "UpperJ": "J",
        "UpperK": "K",
        "UpperL": "L",
        "UpperM": "M",
        "UpperN": "N",
        "UpperO": "O",
        "UpperP": "P",
        "UpperQ": "Q",
        "UpperR": "R",
        "UpperS": "S",
        "UpperT": "T",
        "UpperU": "U",
        "UpperV": "V",
        "UpperW": "W",
        "UpperX": "X",
        "UpperY": "Y",
        "UpperZ": "Z"
    },
    "LowercaseLetterChar": {
        "LowerA": "a",
        "LowerB": "b",
        "LowerC": "c",
        "LowerD": "d",
        "LowerE": "e",
        "LowerF": "f",
        "LowerG": "g",
        "LowerH": "h",
        "LowerI": "i",
        "LowerJ": "j",
        "LowerK": "k",
        "LowerL": "l",
        "LowerM": "m",
        "LowerN": "n",
        "LowerO": "o",
        "LowerP": "p",
        "LowerQ": "q",
        "LowerR": "r",
        "LowerS": "s",
        "LowerT": "t",
        "LowerU": "u",
        "LowerV": "v",
        "LowerW": "w",
        "LowerX": "x",
        "LowerY": "y",
        "LowerZ": "z"
    },
    "DecimalDigitNumberChar": {
        "Number0": "0",
        "Number1": "1",
        "Number2": "2",
        "Number3": "3",
        "Number4": "4",
        "Number5": "5",
        "Number6": "6",
        "Number7": "7",
        "Number8": "8",
        "Number9": "9"
    },
    "SpaceSeparatorChar": {
        "SpaceChar": " ",
        "NoBreakSpaceChar": " ",
        "EnQuadChar": " ",
        "EmQuadChar": " ",
        "EnSpaceChar": " ",
        "EmSpaceChar": " ",
        "ThreePerEmSpaceChar": " ",
        "FourPerEmSpaceChar": " ",
        "SixPerEmSpaceChar": " ",
        "FigureSpaceChar": " ",
        "PunctuationSpaceChar": " ",
        "ThinSpaceChar": " ",
        "HairSpaceChar": " ",
        "MediumMathematicalSpaceChar": " ",
        "IdeographicSpaceChar": "　"
    },
    "LineSeparatorChar": {
        "LineSeparatorChar": " ",
        "UnixLineFeedChar": "\n",
        "WindowsCarriageReturnChar": "\r\n",
        "MacClassicLineFeedChar": "\r"
    },
    "ParagraphSeparatorChar": {
        "ParagraphSeparatorChar": " ",
        "HTMLParagraphBreakChar": "<p>"
    },
    "ControlChar": {
        "NullChar": "\u0000",
        "StartOfHeadingChar": "\u0001",
        "StartOfTextChar": "\u0002",
        "EndOfTextChar": "\u0003",
        "EndOfTransmissionChar": "\u0004",
        "EnquiryChar": "\u0005",
        "AcknowledgeChar": "\u0006",
        "BellChar": "\u0007",
        "BackspaceChar": "\b",
        "TabChar": "\t",
        "VerticalTabChar": "\u000b",
        "FormFeedChar": "\f",
        "EscapeChar": "\u001b"
    },
    "FormatChar": {
        "ZeroWidthSpaceChar": "​",
        "ZeroWidthNonJoinerChar": "‌",
        "ZeroWidthJoinerChar": "‍",
        "WordJoinerChar": "⁠",
        "LeftToRightMarkChar": "‎",
        "RightToLeftMarkChar": "‏",
        "LeftToRightEmbeddingChar": "‪",
        "RightToLeftEmbeddingChar": "‫",
        "LeftToRightOverrideChar": "‭",
        "RightToLeftOverrideChar": "‮",
        "PopDirectionalFormattingChar": "‬",
        "InvisibleSeparatorChar": "⁣",
        "InvisiblePlusChar": "⁤"
    },
    "ConnectorPunctuationChar": {
        "UnderscoreChar": "_",
        "HebrewPunctuationMaqqefChar": "־",
        "UndertieChar": "‿",
        "SpaceConnectorChar": "⁀"
    },
    "DashPunctuationChar": {
        "HyphenMinusChar": "-",
        "EnDashChar": "–",
        "EmDashChar": "—",
        "FigureDashChar": "‒",
        "HorizontalBarChar": "―"
    },
    "OpenPunctuationChar": {
        "LeftParenthesisChar": "(",
        "LeftSquareBracketChar": "[",
        "LeftCurlyBraceChar": "{",
        "LeftAngleBracketChar": "〈",
        "LeftDoubleAngleBracketChar": "«"
    },
    "ClosePunctuationChar": {
        "RightParenthesisChar": ")",
        "RightSquareBracketChar": "]",
        "RightCurlyBraceChar": "}",
        "RightAngleBracketChar": "〉",
        "RightDoubleAngleBracketChar": "»"
    },
    "InitialQuotePunctuationChar": {
        "LeftDoubleQuotationMarkChar": "“",
        "LeftSingleQuotationMarkChar": "‘",
        "ReversedDoublePrimeQuotationMarkChar": "‶",
        "LowDoubleQuotationMarkChar": "„",
        "LowSingleQuotationMarkChar": "‚"
    },
    "FinalQuotePunctuationChar": {
        "RightDoubleQuotationMarkChar": "”",
        "RightSingleQuotationMarkChar": "’",
        "DoublePrimeQuotationMarkChar": "″",
        "HighReversedDoubleQuotationMarkChar": "‷",
        "HighReversedSingleQuotationMarkChar": "‸"
    },
    "OtherPunctuationChar": {
        "ExclamationMarkChar": "!",
        "QuestionMarkChar": "?",
        "PeriodChar": ".",
        "EllipsisChar": "…",
        "MiddleDotChar": "·",
        "InterrobangChar": "‽",
        "BulletChar": "•",
        "QuotationMarkChar": "\"",
        "ApostropheChar": "'"
    },
    "MathSymbolChar": {
        "PlusSignChar": "+",
        "MinusSignChar": "-",
        "MultiplicationSignChar": "×",
        "DivisionSignChar": "÷",
        "EqualSignChar": "=",
        "NotEqualSignChar": "≠",
        "GreaterThanSignChar": ">",
        "LessThanSignChar": "<",
        "GreaterThanOrEqualSignChar": "≥",
        "LessThanOrEqualSignChar": "≤"
    },
    "CurrencySymbolChar": {
        "DollarSignChar": "$",
        "EuroSignChar": "€",
        "PoundSignChar": "£",
        "YenSignChar": "¥",
        "IndianRupeeSignChar": "₹",
        "BitcoinSignChar": "₿",
        "CentSignChar": "¢",
        "KoreanWonSignChar": "₩"
    },
    "ModifierSymbolChar": {
        "CircumflexAccentChar": "^",
        "AcuteAccentChar": "´",
        "GraveAccentChar": "`",
        "TildeChar": "~",
        "MacronChar": "¯",
        "OverlineChar": "‾",
        "BreveChar": "˘",
        "DotAboveChar": "˙",
        "RingAboveChar": "˚"
    },
    "OtherSymbolChar": {
        "AtSignChar": "@",
        "HashSignChar": "#",
        "AmpersandChar": "&",
        "PercentSignChar": "%",
        "StarChar": "★",
        "HeartChar": "♥",
        "MusicNoteChar": "♪",
        "CheckMarkChar": "✓",
        "CrossMarkChar": "✗"
    }
};

charTokenMap = {
    "UpperA": "A",
    "UpperB": "B",
    "UpperC": "C",
    "UpperD": "D",
    "UpperE": "E",
    "UpperF": "F",
    "UpperG": "G",
    "UpperH": "H",
    "UpperI": "I",
    "UpperJ": "J",
    "UpperK": "K",
    "UpperL": "L",
    "UpperM": "M",
    "UpperN": "N",
    "UpperO": "O",
    "UpperP": "P",
    "UpperQ": "Q",
    "UpperR": "R",
    "UpperS": "S",
    "UpperT": "T",
    "UpperU": "U",
    "UpperV": "V",
    "UpperW": "W",
    "UpperX": "X",
    "UpperY": "Y",
    "UpperZ": "Z",
    "LowerA": "a",
    "LowerB": "b",
    "LowerC": "c",
    "LowerD": "d",
    "LowerE": "e",
    "LowerF": "f",
    "LowerG": "g",
    "LowerH": "h",
    "LowerI": "i",
    "LowerJ": "j",
    "LowerK": "k",
    "LowerL": "l",
    "LowerM": "m",
    "LowerN": "n",
    "LowerO": "o",
    "LowerP": "p",
    "LowerQ": "q",
    "LowerR": "r",
    "LowerS": "s",
    "LowerT": "t",
    "LowerU": "u",
    "LowerV": "v",
    "LowerW": "w",
    "LowerX": "x",
    "LowerY": "y",
    "LowerZ": "z",
    "Number0": "0",
    "Number1": "1",
    "Number2": "2",
    "Number3": "3",
    "Number4": "4",
    "Number5": "5",
    "Number6": "6",
    "Number7": "7",
    "Number8": "8",
    "Number9": "9",
    "SpaceChar": " ",
    "NoBreakSpaceChar": " ",
    "EnQuadChar": " ",
    "EmQuadChar": " ",
    "EnSpaceChar": " ",
    "EmSpaceChar": " ",
    "ThreePerEmSpaceChar": " ",
    "FourPerEmSpaceChar": " ",
    "SixPerEmSpaceChar": " ",
    "FigureSpaceChar": " ",
    "PunctuationSpaceChar": " ",
    "ThinSpaceChar": " ",
    "HairSpaceChar": " ",
    "MediumMathematicalSpaceChar": " ",
    "IdeographicSpaceChar": "　",
    "LineSeparatorChar": " ",
    "UnixLineFeedChar": "\n",
    "WindowsCarriageReturnChar": "\r\n",
    "MacClassicLineFeedChar": "\r",
    "ParagraphSeparatorChar": " ",
    "HTMLParagraphBreakChar": "<p>",
    "NullChar": "\u0000",
    "StartOfHeadingChar": "\u0001",
    "StartOfTextChar": "\u0002",
    "EndOfTextChar": "\u0003",
    "EndOfTransmissionChar": "\u0004",
    "EnquiryChar": "\u0005",
    "AcknowledgeChar": "\u0006",
    "BellChar": "\u0007",
    "BackspaceChar": "\b",
    "TabChar": "\t",
    "VerticalTabChar": "\u000b",
    "FormFeedChar": "\f",
    "EscapeChar": "\u001b",
    "ZeroWidthSpaceChar": "​",
    "ZeroWidthNonJoinerChar": "‌",
    "ZeroWidthJoinerChar": "‍",
    "WordJoinerChar": "⁠",
    "LeftToRightMarkChar": "‎",
    "RightToLeftMarkChar": "‏",
    "LeftToRightEmbeddingChar": "‪",
    "RightToLeftEmbeddingChar": "‫",
    "LeftToRightOverrideChar": "‭",
    "RightToLeftOverrideChar": "‮",
    "PopDirectionalFormattingChar": "‬",
    "InvisibleSeparatorChar": "⁣",
    "InvisiblePlusChar": "⁤",
    "UnderscoreChar": "_",
    "HebrewPunctuationMaqqefChar": "־",
    "UndertieChar": "‿",
    "SpaceConnectorChar": "⁀",
    "HyphenMinusChar": "-",
    "EnDashChar": "–",
    "EmDashChar": "—",
    "FigureDashChar": "‒",
    "HorizontalBarChar": "―",
    "LeftParenthesisChar": "(",
    "LeftSquareBracketChar": "[",
    "LeftCurlyBraceChar": "{",
    "LeftAngleBracketChar": "〈",
    "LeftDoubleAngleBracketChar": "«",
    "RightParenthesisChar": ")",
    "RightSquareBracketChar": "]",
    "RightCurlyBraceChar": "}",
    "RightAngleBracketChar": "〉",
    "RightDoubleAngleBracketChar": "»",
    "LeftDoubleQuotationMarkChar": "“",
    "LeftSingleQuotationMarkChar": "‘",
    "ReversedDoublePrimeQuotationMarkChar": "‶",
    "LowDoubleQuotationMarkChar": "„",
    "LowSingleQuotationMarkChar": "‚",
    "RightDoubleQuotationMarkChar": "”",
    "RightSingleQuotationMarkChar": "’",
    "DoublePrimeQuotationMarkChar": "″",
    "HighReversedDoubleQuotationMarkChar": "‷",
    "HighReversedSingleQuotationMarkChar": "‸",
    "ExclamationMarkChar": "!",
    "QuestionMarkChar": "?",
    "PeriodChar": ".",
    "EllipsisChar": "…",
    "MiddleDotChar": "·",
    "InterrobangChar": "‽",
    "BulletChar": "•",
    "QuotationMarkChar": "\"",
    "ApostropheChar": "'",
    "PlusSignChar": "+",
    "MinusSignChar": "-",
    "MultiplicationSignChar": "×",
    "DivisionSignChar": "÷",
    "EqualSignChar": "=",
    "NotEqualSignChar": "≠",
    "GreaterThanSignChar": ">",
    "LessThanSignChar": "<",
    "GreaterThanOrEqualSignChar": "≥",
    "LessThanOrEqualSignChar": "≤",
    "DollarSignChar": "$",
    "EuroSignChar": "€",
    "PoundSignChar": "£",
    "YenSignChar": "¥",
    "IndianRupeeSignChar": "₹",
    "BitcoinSignChar": "₿",
    "CentSignChar": "¢",
    "KoreanWonSignChar": "₩",
    "CircumflexAccentChar": "^",
    "AcuteAccentChar": "´",
    "GraveAccentChar": "`",
    "TildeChar": "~",
    "MacronChar": "¯",
    "OverlineChar": "‾",
    "BreveChar": "˘",
    "DotAboveChar": "˙",
    "RingAboveChar": "˚",
    "AtSignChar": "@",
    "HashSignChar": "#",
    "AmpersandChar": "&",
    "PercentSignChar": "%",
    "StarChar": "★",
    "HeartChar": "♥",
    "MusicNoteChar": "♪",
    "CheckMarkChar": "✓",
    "CrossMarkChar": "✗"
};



/**
 * @param {string} char - Single char look-up value.
 * @returns {string|null} Token Name or null if char not found.
 */
GetTokenName = function(char) {
    return char in charTokenMap ? charTokenMap[char] : null;
}



